In [2]:
import qn
qn.config(globals())

In [12]:
df = pd.DataFrame([[1,2],[3,4],[5,6]],index=['a','b','b'])

In [35]:
indexf = pd.DataFrame([['a','b'],['a','f'],['c','f']],
                     columns=['x','y'])

In [41]:
index = pd.MultiIndex.from_frame(indexf)
cols = pd.MultiIndex.from_frame(indexf.transpose())

In [60]:
idx = pd.IndexSlice

In [47]:
df2 = pd.DataFrame(df.values,
                   index=index)

In [43]:
df2 = pd.DataFrame(df.values,
                   index=index,
                   columns=cols)

In [76]:
df2.loc[idx[['a','a'],['f','b']],:]

     0  1
x y
a f  3  4
  b  1  2

In [86]:
df2.loc[idx['c','f'],:] # shape (2,)

0    5
1    6
Name: (c, f), dtype: int64

In [90]:
df2.loc[idx['a','f'],:] # shape (2,)

0    3
1    4
Name: (a, f), dtype: int64

In [93]:
df2.loc[idx['a',['f','f']],:] # shape (1,2)

     0  1
x y
a f  3  4

In [89]:
df2.loc[idx['c'],:] # shape (1,2)

   0  1
y
f  5  6

In [51]:
df2

     0  1
x y
a b  1  2
  f  3  4
c f  5  6

In [87]:
fk = pd.Series([1,2,3,5],['f','b','f','b'])

In [88]:
fk[['b','f']]

b    2
b    5
f    1
f    3
dtype: int64

In [94]:
fk[['b','b']]

b    2
b    5
b    2
b    5
dtype: int64